server:
  port : 8081
    # ssl:
    # key-store-type: PKCS12
    # key-store: classpath:socialize.p12
    # key-store-password: password
  # key-alias: socialize
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    url: jdbc:postgresql://localhost:5432/eventapi?useSSL=false&serverTimezone=UTC
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #database: POSTGRESQL
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    drop-first: false # Drops and creates scheme from scratch on every start
    change-log: classpath:db/changelog/db.changelog-master.yaml

upload:
  dir: uploads/

external-link:
  #url: "https://socialize-fe.netlify.app/images/"
  url: "http://localhost:8081/images/"
  server-mail-url: "http://localhost:8081/api/v1/events/confirm"